start:
	go run ./cmd/something
start_internal:
	#go run ./internal/notes.go
	go run ./internal/fruit-api.go
build:
	go build -o ./build/something ./cmd/something
test:
	go test ./...
clean:
	rm -rf ./build